server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/mindsystem?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info
voiceMind:
  jwt:
    secret-key: 3iVGzOxZ0zZfC3CXDzyrMpmd4LzU7SnW05KzrmsXUVU=
    expiration-millis: 3600000

model:
  path: F:/VoiceMindServer/src/main/resources/pth
  inputSize: 520
  name: binary_classifier
upload:
  folder: src/main/resources/data

tencent:
  cos:
    secret-id: your-secret-id
    secret-key: your-secret-key
    bucket-name: your-bucket-name
    region: ap-beijing
    prefix: audio/  # 上传的文件统一前缀（可选）