spring:
  datasource:
    url: jdbc:mysql://192.168.0.100:3306/mindsystem?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
logging:
  level:
    com:
      sky:
        service: debug
